import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import DevBanner from "@/components/DevBanner";
import DiagBanner from "@/components/DiagBanner";
import BuildBadge from "@/components/BuildBadge";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DevBanner />
        {process.env.NEXT_PUBLIC_ENABLE_ADMIN_BANNER !== '0' && <DiagBanner />}
        <Header />
        {children}
        <BuildBadge />
      </body>
    </html>
  );
}
