import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import DevBanner from "@/components/DevBanner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sha = (process.env.VERCEL_GIT_COMMIT_SHA || "unknown").slice(0,7);
  const marker = "FST-RIG-TS-FP";
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DevBanner />
        <Header />
        {children}
        <footer style={{
          marginTop:"2rem",
          padding:"0.75rem 1rem",
          fontSize:"12px",
          opacity:0.6,
          borderTop:"1px solid rgba(255,255,255,0.1)"
        }}>
          <span>build: <code>{sha}</code></span>
          <span style={{marginLeft:12}}>marker: <code>{marker}</code></span>
        </footer>
      </body>
    </html>
  );
}
